ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: ${PORT:8080}

firebase:
    projectId: ${FIREBASE_PROJECT_ID}
    serviceAccountJson: ${FIREBASE_SERVICE_ACCOUNT_JSON}
